apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec
spec:
  containers:
  - name: liveness
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command: ["sh", "-c", "sleep 3600"]
    #Liveness probes
    livenessProbe:
      #Liveness command
      exec:
        command:
        - sh
        - -c
        - echo ok
      initialDelaySeconds: 5
      periodSeconds: 5

      #Liveness http request
      httpGet:
        path: /healthz
        port: 8080
        httpHeaders:
        - name: X-custom-Header
          value: Awesome
      initialDelaySeconds: 15
      periodSeconds: 5

      #TCP Liveness probe
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 5

      #gRPC Liveness probe
      grpc:
        port: 2379
      initialDelaySeconds: 10

      #Readiness probes (Can also be defined as command, HTTP request, TCP or gRPC)
      readinessProbe:
        exec:
          command:
          - cat
          - /tmp/healthy
        initailDelaySeconds: 5
        periodSeconds: 5
